#!/bin/bash


 git config --global user.name "zhiguangjia"

 git config --global user.email  "jzg579@gmail.com"


     git init

     git add .

     git remote add origin https://github.com/zhiguangjia/BK_vapor_barrier

           # need build in webpage before this

     git remote -v

     git pull origin master
           # connect to the github 

    git push origin master














